[[plugins]]
  package = "netlify-plugin-flutter"

[build]
  publish = "build/web"
  command = "flutter build web --release --no-tree-shake-icons"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
